### ISSUE TITLE
Supply option to prevent typescript-simple from throwing an exception on compiler errors

### ISSUE THREAD

**Issue by DanielRosenwasser** [teppeis/typescript-simple#14]
In cases where downlevel emit is more interesting than errors, it would be desirable to just return TypeScript's emit, especially since TypeScript emits in the face of errors.

**Comment by basarat** [comment]
Already done as a part of #7

**Comment by basarat** [comment]
https://github.com/basarat/typescript-simple/commit/7503d1447606d13c8103d268ecc9242874ff750f

**Comment by DanielRosenwasser** [comment]
Whoops, thanks guys!

**Comment by teppeis** [comment]
@DanielRosenwasser Use `doSemanticChecks` by @basarat ! thanks.
