### ISSUE TITLE
Allow user to bring their own version of typescript

### ISSUE THREAD

**Issue by alexeagle** [teppeis/typescript-simple#17]
eg. right now typescript is at 1.5.0-alpha, but this package is at 1.4.
See https://github.com/ivogabe/gulp-typescript/issues/63

note that there are some breaking API changes in ts 1.5 so this isn't trivial.

**Comment by teppeis** [comment]
TypeScript 1.5 has breaking changes about Compiler API too, so it's not simple to support for both TS 1.4 and 1.5 in same package.
And almost TypeScript users will migrate to 1.5 soon after TypeScript 1.5 released.

So I'm planning to release typescript-simple@2.0.0(-alpha) for typescript@1.5.0(-alpha). Users that want to use TS 1.4 can specify `^1.0.0` as typescript-simple in package.json.

**Comment by alexeagle** [comment]
Fair enough, it's easier to keep this in separate branches.
Even if your 2.0.0 only supports TS 1.5, it would still be nice to mark TS as a peerDependency, in case we have local modifications or branch of the typescript project.

**Comment by teppeis** [comment]
typescript-simple@8 supports TypeScript v2.2-v2.4.
If TS doesn't have ***major*** breaking changes, typescript-simple allows users to bring their own version of typescript.
