### ISSUE TITLE
Using in browser

### ISSUE THREAD

**Issue by tomitrescak** [teppeis/typescript-simple#22]
Hi, great package! 
Was wondering if it possible to use this in browser?
I have online typescript editor and want to compile it in browser to javascript.
Do you think your package can do this?
I have a strong feeling that yes ;) 
Just not sure how to approach it.

Thanks

**Comment by teppeis** [comment]
@tomitrescak There is only one issue about`fs` package.
It loads default lib: https://github.com/teppeis/typescript-simple/blob/f74d1cf307e4ea8b6d4b1130e76a4a13d621dfc1/index.ts#L63, but it doesn't work in browsers as-is.

You could use typescript-simple in browsers with browserify hack for the issue, but I don't know the solution now.
thanks.

**Comment by basarat** [comment]
There is typescript-script : https://github.com/basarat/typescript-script

**Comment by teppeis** [comment]
@basarat :+1:

**Comment by tomitrescak** [comment]
Nice. Yet, unfortunatelly this only transpiles the typescript, while I need a full compilation results. Already managed to do it with typescript-compiler. Thanks anyways!
