### ISSUE TITLE
Allow resolving files on the fly to enable use in typescript preprocessors

### ISSUE THREAD

**Issue by sergeyt** [teppeis/typescript-simple#42]
I use [slightly modified version](https://github.com/sergeyt/typescript-simple/commit/4c208a9eec0345fd9d5c08c6e85af69c6b80ce58) of this module in [karma-typescript-preprocessor](https://github.com/sergeyt/karma-typescript-preprocessor). Please consider to add support for resolving referenced files on the fly e.g. via some callback function.

**Comment by teppeis** [comment]
@sergeyt What is the use case? If you ignore semantic check, you don't have to resolve referenced files.

**Comment by sergeyt** [comment]
@teppeis thanks, I am going to use this option for now.

**Comment by teppeis** [comment]
@sergeyt thanks!
