### ISSUE TITLE
How fast is it compared to CoffeScript compile

### ISSUE THREAD

**Issue by basarat** [teppeis/typescript-simple#5]
Just curious if you've compared. Basically does it do *semantic* validation? Could we switch that off and just do the syntactic one (needed for valid emit).

**Comment by teppeis** [comment]
@basarat This is simple benchmark of typescript-simple vs. coffee-script
https://gist.github.com/teppeis/68baae014137778b76c4

For 200 times compilation of tiny equivalent code, typescript-simple is 60% slower than coffee-script.

* typescript-simple 1264ms
* coffee-script 798ms

but typescript-simple requires additional 500ms for warm up at first time.

> Basically does it do semantic validation? Could we switch that off and just do the syntactic one (needed for valid emit).

Sure!  typescript-simple checks semantics (static typing) and throws an error if it's invalid.
But I cannot find the way to switch that off in TypeScript 1.4 Compiler API.

**Comment by basarat** [comment]
:heart:
